import { useMemo, useRef, useState } from "react";
import "./App.css";

const initialClinicalData = {
  age: "",
  sex: "",
  symptoms: "",
  bloodPressure: "",
  heartRate: "",
  diabetes: false,
  hypertension: false,
  smoking: false,
};

const modalityConfig = {
  echo: {
    label: "Echocardiography",
    short: "ECHO",
    description: "2D cardiac ultrasound",
    accept: ".png,.jpg,.jpeg,.dcm,.nii,.nii.gz",
  },
  ccta: {
    label: "Coronary CT Angiography",
    short: "CCTA",
    description: "Cardiac CT / coronary anatomy",
    accept: ".dcm,.nii,.nii.gz,.zip,.png,.jpg,.jpeg",
  },
  ecg: {
    label: "Electrocardiography",
    short: "ECG",
    description: "ECG waveform / report",
    accept: ".png,.jpg,.jpeg,.pdf,.csv",
  },
};

function App() {
  const [clinicalData, setClinicalData] = useState(initialClinicalData);
  const [files, setFiles] = useState({
    echo: null,
    ccta: null,
    ecg: null,
  });

  const [activeSection, setActiveSection] = useState("case");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisComplete, setAnalysisComplete] = useState(false);
  const [activeResult, setActiveResult] = useState("overview");
  const [question, setQuestion] = useState("");
  const [conversation, setConversation] = useState([]);
  const [showClinicalForm, setShowClinicalForm] = useState(true);

  const echoInput = useRef(null);
  const cctaInput = useRef(null);
  const ecgInput = useRef(null);

  const patientId = useMemo(
    () => `CV-${new Date().getFullYear()}-001`,
    []
  );

  const uploadedCount = Object.values(files).filter(Boolean).length;

  const hasClinicalData = Object.values(clinicalData).some(
    (value) => value !== "" && value !== false
  );

  const canAnalyze = uploadedCount > 0 || hasClinicalData;

  const updateClinical = (field, value) => {
    setClinicalData((previous) => ({
      ...previous,
      [field]: value,
    }));
  };

  const handleFile = (modality, file) => {
    if (!file) return;

    setFiles((previous) => ({
      ...previous,
      [modality]: file,
    }));

    setAnalysisComplete(false);
  };

  const removeFile = (modality) => {
    setFiles((previous) => ({
      ...previous,
      [modality]: null,
    }));

    setAnalysisComplete(false);
  };

  const runAnalysis = () => {
    if (!canAnalyze) return;

    setIsAnalyzing(true);
    setActiveSection("results");

    setTimeout(() => {
      setIsAnalyzing(false);
      setAnalysisComplete(true);
      setActiveResult("overview");
    }, 2200);
  };

  const askQuestion = () => {
    const trimmed = question.trim();

    if (!trimmed) return;

    setConversation((previous) => [
      ...previous,
      {
        role: "user",
        text: trimmed,
      },
      {
        role: "assistant",
        text:
          "This case-level response will be generated by the local medical language model after the multimodal inference pipeline is connected.",
      },
    ]);

    setQuestion("");
  };

  const scrollToSection = (section) => {
    setActiveSection(section);

    const element = document.getElementById(section);

    if (element) {
      element.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }
  };

  return (
    <div className="cv-app">
      <header className="cv-header">
        <div className="cv-brand">
          <div className="cv-brand-mark">
            CV
          </div>

          <div>
            <div className="cv-brand-name">
              CardioVision
            </div>

            <div className="cv-brand-subtitle">
              Multimodal Cardiovascular Intelligence
            </div>
          </div>
        </div>

        <div className="cv-header-center">
          <span className="cv-system-dot" />
          LOCAL RESEARCH SYSTEM
        </div>

        <div className="cv-header-actions">
          <button
            className="cv-header-button"
            onClick={() => scrollToSection("case")}
          >
            New Case
          </button>

          <div className="cv-user-avatar">
            MH
          </div>
        </div>
      </header>

      <div className="cv-layout">
        <aside className="cv-sidebar">
          <div className="cv-sidebar-label">
            WORKSPACE
          </div>

          <button
            className={`cv-nav-item ${
              activeSection === "case" ? "active" : ""
            }`}
            onClick={() => scrollToSection("case")}
          >
            <span className="cv-nav-number">01</span>
            <span>Patient Case</span>
          </button>

          <button
            className={`cv-nav-item ${
              activeSection === "results" ? "active" : ""
            }`}
            onClick={() => scrollToSection("results")}
          >
            <span className="cv-nav-number">02</span>
            <span>Analysis</span>
          </button>

          <button
            className={`cv-nav-item ${
              activeSection === "explainability" ? "active" : ""
            }`}
            onClick={() => scrollToSection("explainability")}
          >
            <span className="cv-nav-number">03</span>
            <span>Explainability</span>
          </button>

          <button
            className={`cv-nav-item ${
              activeSection === "assistant" ? "active" : ""
            }`}
            onClick={() => scrollToSection("assistant")}
          >
            <span className="cv-nav-number">04</span>
            <span>Case Assistant</span>
          </button>

          <div className="cv-sidebar-spacer" />

          <div className="cv-local-card">
            <div className="cv-local-icon">
              ◉
            </div>

            <div>
              <div className="cv-local-title">
                Local inference
              </div>

              <div className="cv-local-text">
                Patient data remains on device.
              </div>
            </div>
          </div>
        </aside>

        <main className="cv-main">
          <section className="cv-hero">
            <div className="cv-eyebrow">
              CARDIOVASCULAR AI PLATFORM
            </div>

            <h1>
              Understand the heart
              <br />
              <span>through multimodal AI.</span>
            </h1>

            <p>
              Analyze clinical information, echocardiography,
              CCTA, and ECG data within a unified patient case.
              Generate model predictions, structural analysis,
              visual explanations, and case-level AI assistance.
            </p>

            <div className="cv-hero-meta">
              <div>
                <span className="cv-meta-label">
                  SYSTEM
                </span>
                <strong>CardioVision AI</strong>
              </div>

              <div>
                <span className="cv-meta-label">
                  INFERENCE
                </span>
                <strong>Local</strong>
              </div>

              <div>
                <span className="cv-meta-label">
                  MODALITIES
                </span>
                <strong>Clinical · Echo · CCTA · ECG</strong>
              </div>
            </div>
          </section>

          <section
            id="case"
            className="cv-section"
          >
            <div className="cv-section-heading">
              <div>
                <div className="cv-section-index">
                  01 / PATIENT CASE
                </div>

                <h2>
                  Build a clinical case
                </h2>

                <p>
                  Provide the available patient information and
                  imaging studies. Missing modalities can remain
                  unprovided.
                </p>
              </div>

              <div className="cv-case-id">
                <span>CASE ID</span>
                <strong>{patientId}</strong>
              </div>
            </div>

            <div className="cv-case-grid">
              <div className="cv-clinical-card">
                <div className="cv-card-header">
                  <div>
                    <span className="cv-card-kicker">
                      CLINICAL DATA
                    </span>

                    <h3>
                      Patient information
                    </h3>
                  </div>

                  <button
                    className="cv-text-button"
                    onClick={() =>
                      setShowClinicalForm((value) => !value)
                    }
                  >
                    {showClinicalForm ? "Collapse" : "Edit"}
                  </button>
                </div>

                {showClinicalForm && (
                  <div className="cv-form">
                    <div className="cv-form-row">
                      <label>
                        Age
                        <input
                          type="number"
                          placeholder="e.g. 58"
                          value={clinicalData.age}
                          onChange={(event) =>
                            updateClinical(
                              "age",
                              event.target.value
                            )
                          }
                        />
                      </label>

                      <label>
                        Sex
                        <select
                          value={clinicalData.sex}
                          onChange={(event) =>
                            updateClinical(
                              "sex",
                              event.target.value
                            )
                          }
                        >
                          <option value="">
                            Select
                          </option>
                          <option value="Male">
                            Male
                          </option>
                          <option value="Female">
                            Female
                          </option>
                        </select>
                      </label>
                    </div>

                    <label>
                      Primary symptoms
                      <textarea
                        rows="3"
                        placeholder="Chest pain, dyspnea, fatigue..."
                        value={clinicalData.symptoms}
                        onChange={(event) =>
                          updateClinical(
                            "symptoms",
                            event.target.value
                          )
                        }
                      />
                    </label>

                    <div className="cv-form-row">
                      <label>
                        Blood pressure
                        <input
                          type="text"
                          placeholder="120/80"
                          value={clinicalData.bloodPressure}
                          onChange={(event) =>
                            updateClinical(
                              "bloodPressure",
                              event.target.value
                            )
                          }
                        />
                      </label>

                      <label>
                        Heart rate
                        <input
                          type="number"
                          placeholder="72 bpm"
                          value={clinicalData.heartRate}
                          onChange={(event) =>
                            updateClinical(
                              "heartRate",
                              event.target.value
                            )
                          }
                        />
                      </label>
                    </div>

                    <div className="cv-checkbox-grid">
                      <label className="cv-checkbox">
                        <input
                          type="checkbox"
                          checked={clinicalData.diabetes}
                          onChange={(event) =>
                            updateClinical(
                              "diabetes",
                              event.target.checked
                            )
                          }
                        />
                        <span>Diabetes</span>
                      </label>

                      <label className="cv-checkbox">
                        <input
                          type="checkbox"
                          checked={clinicalData.hypertension}
                          onChange={(event) =>
                            updateClinical(
                              "hypertension",
                              event.target.checked
                            )
                          }
                        />
                        <span>Hypertension</span>
                      </label>

                      <label className="cv-checkbox">
                        <input
                          type="checkbox"
                          checked={clinicalData.smoking}
                          onChange={(event) =>
                            updateClinical(
                              "smoking",
                              event.target.checked
                            )
                          }
                        />
                        <span>Smoking</span>
                      </label>
                    </div>
                  </div>
                )}
              </div>

              <div className="cv-modalities">
                {Object.entries(modalityConfig).map(
                  ([key, modality]) => (
                    <ModalityCard
                      key={key}
                      modality={modality}
                      file={files[key]}
                      inputRef={
                        key === "echo"
                          ? echoInput
                          : key === "ccta"
                          ? cctaInput
                          : ecgInput
                      }
                      onUpload={(file) =>
                        handleFile(key, file)
                      }
                      onRemove={() =>
                        removeFile(key)
                      }
                    />
                  )
                )}
              </div>
            </div>

            <div className="cv-analysis-bar">
              <div>
                <div className="cv-analysis-title">
                  Ready for multimodal analysis
                </div>

                <div className="cv-analysis-subtitle">
                  {uploadedCount} imaging modality
                  {uploadedCount !== 1 ? "ies" : "y"} provided
                  {hasClinicalData
                    ? " · Clinical data available"
                    : ""}
                </div>
              </div>

              <button
                className="cv-primary-button"
                disabled={!canAnalyze || isAnalyzing}
                onClick={runAnalysis}
              >
                {isAnalyzing
                  ? "Analyzing case..."
                  : "Analyze Case"}
                <span>→</span>
              </button>
            </div>
          </section>

          <section
            id="results"
            className="cv-section"
          >
            <div className="cv-section-heading">
              <div>
                <div className="cv-section-index">
                  02 / MULTIMODAL ANALYSIS
                </div>

                <h2>
                  Case intelligence
                </h2>

                <p>
                  A unified workspace for modality-specific
                  inference and multimodal interpretation.
                </p>
              </div>

              <div className="cv-analysis-status">
                <span
                  className={
                    analysisComplete
                      ? "complete"
                      : "pending"
                  }
                />
                {analysisComplete
                  ? "Analysis complete"
                  : "Awaiting analysis"}
              </div>
            </div>

            {!analysisComplete && !isAnalyzing && (
              <div className="cv-empty-analysis">
                <div className="cv-empty-icon">
                  ◌
                </div>

                <h3>
                  No analysis generated yet
                </h3>

                <p>
                  Add patient information or imaging data above,
                  then run the analysis pipeline.
                </p>

                <button
                  className="cv-secondary-button"
                  onClick={() =>
                    scrollToSection("case")
                  }
                >
                  Configure patient case
                </button>
              </div>
            )}

            {isAnalyzing && (
              <AnalysisLoader />
            )}

            {analysisComplete && (
              <div className="cv-results">
                <div className="cv-result-navigation">
                  <button
                    className={
                      activeResult === "overview"
                        ? "active"
                        : ""
                    }
                    onClick={() =>
                      setActiveResult("overview")
                    }
                  >
                    Overview
                  </button>

                  <button
                    className={
                      activeResult === "echo"
                        ? "active"
                        : ""
                    }
                    onClick={() =>
                      setActiveResult("echo")
                    }
                  >
                    Echo
                  </button>

                  <button
                    className={
                      activeResult === "ccta"
                        ? "active"
                        : ""
                    }
                    onClick={() =>
                      setActiveResult("ccta")
                    }
                  >
                    CCTA
                  </button>

                  <button
                    className={
                      activeResult === "clinical"
                        ? "active"
                        : ""
                    }
                    onClick={() =>
                      setActiveResult("clinical")
                    }
                  >
                    Clinical
                  </button>
                </div>

                {activeResult === "overview" && (
                  <OverviewResult
                    files={files}
                    clinicalData={clinicalData}
                  />
                )}

                {activeResult === "echo" && (
                  <EchoResult file={files.echo} />
                )}

                {activeResult === "ccta" && (
                  <CCTAResult file={files.ccta} />
                )}

                {activeResult === "clinical" && (
                  <ClinicalResult
                    clinicalData={clinicalData}
                  />
                )}
              </div>
            )}
          </section>

          {analysisComplete && (
            <>
              <section
                id="explainability"
                className="cv-section"
              >
                <div className="cv-section-heading">
                  <div>
                    <div className="cv-section-index">
                      03 / EXPLAINABILITY
                    </div>

                    <h2>
                      See why the model predicts
                    </h2>

                    <p>
                      Model explanations connect predictions
                      with relevant image regions and anatomical
                      structures.
                    </p>
                  </div>
                </div>

                <div className="cv-xai-grid">
                  <div className="cv-xai-image">
                    <div className="cv-image-placeholder cv-heatmap">
                      <div className="cv-heatmap-ring" />
                      <div className="cv-image-overlay-label">
                        GRAD-CAM
                      </div>
                    </div>

                    <div className="cv-image-caption">
                      <strong>
                        Prediction attribution
                      </strong>
                      <span>
                        Regions contributing to the selected
                        prediction
                      </span>
                    </div>
                  </div>

                  <div className="cv-xai-content">
                    <span className="cv-card-kicker">
                      MODEL EXPLANATION
                    </span>

                    <h3>
                      Coronary abnormality
                    </h3>

                    <div className="cv-confidence">
                      <div>
                        <span>
                          Model confidence
                        </span>
                        <strong>
                          87.4%
                        </strong>
                      </div>

                      <div className="cv-confidence-bar">
                        <span style={{ width: "87.4%" }} />
                      </div>
                    </div>

                    <div className="cv-finding-list">
                      <Finding
                        title="Coronary anatomy"
                        value="Relevant region detected"
                      />

                      <Finding
                        title="Cardiac structure"
                        value="Left ventricular region"
                      />

                      <Finding
                        title="Model attention"
                        value="High regional contribution"
                      />
                    </div>

                    <div className="cv-xai-note">
                      Explainability outputs are intended to
                      show model attribution and should not be
                      interpreted as independent clinical
                      evidence.
                    </div>
                  </div>
                </div>

                <div className="cv-segmentation-card">
                  <div>
                    <span className="cv-card-kicker">
                      STRUCTURAL ANALYSIS
                    </span>

                    <h3>
                      Cardiovascular segmentation
                    </h3>

                    <p>
                      Predicted anatomical structures can be
                      visualized alongside the original imaging
                      data.
                    </p>
                  </div>

                  <div className="cv-segmentation-visual">
                    <div className="cv-anatomy-placeholder">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="cv-segmentation-legend">
                      <span>
                        <i />
                        Coronary vessel
                      </span>

                      <span>
                        <i />
                        Cardiac structure
                      </span>

                      <span>
                        <i />
                        Segmentation region
                      </span>
                    </div>
                  </div>
                </div>
              </section>

              <section
                id="assistant"
                className="cv-section cv-assistant-section"
              >
                <div className="cv-section-heading">
                  <div>
                    <div className="cv-section-index">
                      04 / CASE ASSISTANT
                    </div>

                    <h2>
                      Ask about this case
                    </h2>

                    <p>
                      Query the local medical language model
                      using the available case context and
                      model-generated findings.
                    </p>
                  </div>

                  <div className="cv-local-badge">
                    <span />
                    LOCAL MEDICAL MODEL
                  </div>
                </div>

                <div className="cv-assistant">
                  <div className="cv-assistant-context">
                    <div className="cv-assistant-context-header">
                      <span className="cv-card-kicker">
                        CASE CONTEXT
                      </span>

                      <span className="cv-context-status">
                        Context loaded
                      </span>
                    </div>

                    <div className="cv-context-items">
                      <ContextItem
                        label="Clinical"
                        active={hasClinicalData}
                      />

                      <ContextItem
                        label="Echocardiography"
                        active={Boolean(files.echo)}
                      />

                      <ContextItem
                        label="CCTA"
                        active={Boolean(files.ccta)}
                      />

                      <ContextItem
                        label="ECG"
                        active={Boolean(files.ecg)}
                      />

                      <ContextItem
                        label="AI findings"
                        active={analysisComplete}
                      />
                    </div>
                  </div>

                  <div className="cv-chat">
                    {conversation.length === 0 ? (
                      <div className="cv-chat-empty">
                        <div className="cv-chat-icon">
                          +
                        </div>

                        <h3>
                          Ask a clinical question
                        </h3>

                        <p>
                          Ask the local model to summarize,
                          explain, or reason over the available
                          case information.
                        </p>

                        <div className="cv-question-suggestions">
                          <button
                            onClick={() =>
                              setQuestion(
                                "What are the main findings in this case?"
                              )
                            }
                          >
                            Summarize the findings
                          </button>

                          <button
                            onClick={() =>
                              setQuestion(
                                "What findings require further attention?"
                              )
                            }
                          >
                            What needs attention?
                          </button>

                          <button
                            onClick={() =>
                              setQuestion(
                                "Explain the imaging findings."
                              )
                            }
                          >
                            Explain the imaging
                          </button>
                        </div>
                      </div>
                    ) : (
                      <div className="cv-conversation">
                        {conversation.map(
                          (message, index) => (
                            <div
                              key={index}
                              className={`cv-message ${
                                message.role
                              }`}
                            >
                              <div className="cv-message-role">
                                {message.role === "user"
                                  ? "YOU"
                                  : "CARDIOVISION"}
                              </div>

                              <div className="cv-message-text">
                                {message.text}
                              </div>
                            </div>
                          )
                        )}
                      </div>
                    )}

                    <div className="cv-chat-input">
                      <textarea
                        rows="2"
                        placeholder="Ask about this patient case..."
                        value={question}
                        onChange={(event) =>
                          setQuestion(
                            event.target.value
                          )
                        }
                        onKeyDown={(event) => {
                          if (
                            event.key === "Enter" &&
                            !event.shiftKey
                          ) {
                            event.preventDefault();
                            askQuestion();
                          }
                        }}
                      />

                      <button
                        onClick={askQuestion}
                        disabled={!question.trim()}
                      >
                        Ask
                        <span>→</span>
                      </button>
                    </div>
                  </div>
                </div>
              </section>
            </>
          )}

          <footer className="cv-footer">
            <div>
              <strong>
                CardioVision AI
              </strong>

              <span>
                Multimodal cardiovascular imaging research
                platform
              </span>
            </div>

            <div>
              Research prototype · Local inference
            </div>
          </footer>
        </main>
      </div>
    </div>
  );
}

function ModalityCard({
  modality,
  file,
  inputRef,
  onUpload,
  onRemove,
}) {
  return (
    <div
      className={`cv-modality-card ${
        file ? "uploaded" : ""
      }`}
    >
      <div className="cv-modality-top">
        <div className="cv-modality-icon">
          {modality.short}
        </div>

        {file && (
          <span className="cv-uploaded-badge">
            READY
          </span>
        )}
      </div>

      <div className="cv-modality-title">
        {modality.label}
      </div>

      <div className="cv-modality-description">
        {modality.description}
      </div>

      {file ? (
        <div className="cv-file">
          <div className="cv-file-icon">
            IMG
          </div>

          <div className="cv-file-info">
            <strong>
              {file.name}
            </strong>

            <span>
              {(file.size / 1024 / 1024).toFixed(2)} MB
            </span>
          </div>

          <button
            className="cv-remove-button"
            onClick={onRemove}
          >
            ×
          </button>
        </div>
      ) : (
        <>
          <input
            ref={inputRef}
            type="file"
            accept={modality.accept}
            hidden
            onChange={(event) =>
              onUpload(event.target.files[0])
            }
          />

          <button
            className="cv-upload-button"
            onClick={() => inputRef.current?.click()}
          >
            <span>+</span>
            Upload data
          </button>
        </>
      )}
    </div>
  );
}

function AnalysisLoader() {
  return (
    <div className="cv-analysis-loader">
      <div className="cv-loader-spinner" />

      <div>
        <h3>
          Running multimodal analysis
        </h3>

        <p>
          Processing the available patient data through
          modality-specific models and preparing the fusion
          context.
        </p>
      </div>

      <div className="cv-loader-steps">
        <LoaderStep
          number="01"
          text="Preprocessing"
          active
        />

        <LoaderStep
          number="02"
          text="Modality inference"
          active
        />

        <LoaderStep
          number="03"
          text="Multimodal reasoning"
        />

        <LoaderStep
          number="04"
          text="Explainability"
        />
      </div>
    </div>
  );
}

function LoaderStep({ number, text, active }) {
  return (
    <div className={`cv-loader-step ${active ? "active" : ""}`}>
      <span>{number}</span>
      {text}
    </div>
  );
}

function OverviewResult({
  files,
  clinicalData,
}) {
  return (
    <div className="cv-overview">
      <div className="cv-summary-card">
        <div className="cv-summary-main">
          <span className="cv-card-kicker">
            PRIMARY MODEL FINDING
          </span>

          <h3>
            Cardiovascular abnormality detected
          </h3>

          <p>
            The available case information indicates findings
            that warrant further clinical review. The result
            shown here represents a research model output.
          </p>
        </div>

        <div className="cv-summary-confidence">
          <span>CONFIDENCE</span>
          <strong>87.4%</strong>
        </div>
      </div>

      <div className="cv-metric-grid">
        <Metric
          label="Clinical risk"
          value="Elevated"
        />

        <Metric
          label="Echo finding"
          value={files.echo ? "Analyzed" : "Not provided"}
        />

        <Metric
          label="CCTA finding"
          value={files.ccta ? "Analyzed" : "Not provided"}
        />

        <Metric
          label="ECG"
          value={files.ecg ? "Analyzed" : "Not provided"}
        />
      </div>

      <div className="cv-findings-grid">
        <div className="cv-finding-card">
          <span className="cv-card-kicker">
            KEY FINDINGS
          </span>

          <Finding
            title="Coronary anatomy"
            value="Potential abnormality"
          />

          <Finding
            title="Cardiac function"
            value="Requires review"
          />

          <Finding
            title="Clinical profile"
            value={
              clinicalData.hypertension
                ? "Hypertension reported"
                : "Available data reviewed"
            }
          />
        </div>

        <div className="cv-finding-card">
          <span className="cv-card-kicker">
            NEXT STEP
          </span>

          <h3>
            Review model evidence
          </h3>

          <p>
            Inspect modality-specific outputs and
            explainability visualizations before drawing any
            clinical conclusion.
          </p>
        </div>
      </div>
    </div>
  );
}

function EchoResult({ file }) {
  return (
    <div className="cv-modality-result">
      <ResultVisual
        title="Echocardiography analysis"
        subtitle={
          file
            ? `Analyzed: ${file.name}`
            : "No echocardiography file provided"
        }
      />

      <div className="cv-result-detail">
        <span className="cv-card-kicker">
          ECHO MODEL
        </span>

        <h3>
          Cardiac structure and function
        </h3>

        <p>
          The trained echocardiography model will provide
          cardiac structure segmentation and relevant
          prediction outputs here.
        </p>

        <div className="cv-result-stat-row">
          <Metric
            label="LV segmentation"
            value="Available"
          />

          <Metric
            label="Model confidence"
            value="84.2%"
          />
        </div>
      </div>
    </div>
  );
}

function CCTAResult({ file }) {
  return (
    <div className="cv-modality-result">
      <ResultVisual
        title="CCTA analysis"
        subtitle={
          file
            ? `Analyzed: ${file.name}`
            : "No CCTA file provided"
        }
      />

      <div className="cv-result-detail">
        <span className="cv-card-kicker">
          CCTA MODEL
        </span>

        <h3>
          Coronary anatomy
        </h3>

        <p>
          The CCTA model will provide coronary and
          cardiovascular structure segmentation together with
          disease-related imaging findings.
        </p>

        <div className="cv-result-stat-row">
          <Metric
            label="Anatomical analysis"
            value="Available"
          />

          <Metric
            label="Model confidence"
            value="89.1%"
          />
        </div>
      </div>
    </div>
  );
}

function ClinicalResult({ clinicalData }) {
  return (
    <div className="cv-clinical-result">
      <div>
        <span className="cv-card-kicker">
          CLINICAL MODEL
        </span>

        <h3>
          Patient-level clinical assessment
        </h3>

        <p>
          Structured clinical variables are processed by the
          clinical prediction model and can contribute to the
          multimodal case representation.
        </p>
      </div>

      <div className="cv-clinical-values">
        <Metric
          label="Age"
          value={clinicalData.age || "Not provided"}
        />

        <Metric
          label="Sex"
          value={clinicalData.sex || "Not provided"}
        />

        <Metric
          label="Blood pressure"
          value={
            clinicalData.bloodPressure ||
            "Not provided"
          }
        />

        <Metric
          label="Heart rate"
          value={
            clinicalData.heartRate
              ? `${clinicalData.heartRate} bpm`
              : "Not provided"
          }
        />
      </div>
    </div>
  );
}

function ResultVisual({
  title,
  subtitle,
}) {
  return (
    <div className="cv-result-visual">
      <div className="cv-result-visual-image">
        <div className="cv-scan-grid">
          <div />
          <div />
          <div />
        </div>

        <span>
          MODEL OUTPUT
        </span>
      </div>

      <div className="cv-result-visual-caption">
        <strong>{title}</strong>
        <span>{subtitle}</span>
      </div>
    </div>
  );
}

function Metric({ label, value }) {
  return (
    <div className="cv-metric">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

function Finding({ title, value }) {
  return (
    <div className="cv-finding">
      <div className="cv-finding-check">
        ✓
      </div>

      <div>
        <strong>{title}</strong>
        <span>{value}</span>
      </div>
    </div>
  );
}

function ContextItem({ label, active }) {
  return (
    <div className={`cv-context-item ${active ? "active" : ""}`}>
      <span>{active ? "✓" : "○"}</span>
      {label}
    </div>
  );
}

export default App;